apiVersion: v1
kind: Service
metadata: 
  name: sample-svc
  labels:
    app: sample-ctr
spec:
  type: NodePort
  ports: 
  - port: 8080
    nodePort: 30005
    protocol: TCP
  selector:
    app: kubernetes-configmap-reload


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-configmap-reload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-configmap-reload
  template:
    metadata:
      labels:
        app: kubernetes-configmap-reload
    spec:
      containers:
        - name: kubernetes-configmap-reload
          image: praveensingam1994/kubernetes-configmap-reload:latest

# kind: Service
# apiVersion: v1
# metadata:
#   name: kubernetes-configmap-reload
# spec:
#   type: NodePort
#   ports: 
#   - port: 8080
#     nodePort: 30005
#     protocol: TCP  
#  selector:
#     app: kubernetes-configmap-reload
#     # spec:
# #   type: nodeport
# #   ports:
# #     - name: http
# #       protocol: TCP
# #       # ELB's port
# #       port: 8081
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kubernetes-configmap-reload
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: kubernetes-configmap-reload
#   template:
#     metadata:
#       labels:
#         app: kubernetes-configmap-reload
#     spec:
#       containers:
#         - name: kubernetes-configmap-reload
#           image: praveensingam1994/kubernetes-configmap-reload:latest
